surface_detection:
  frame_id: world_frame
  k_search: 20
  marker_alpha: 0.6

  stout_mean: 10
  stout_stdev_threshold: 4.0

  rg_min_cluster_size: 100
  rg_max_cluster_size: 10000
  rg_neighbors: 20
  rg_smoothness_threshold: 0.08
  rg_curvature_threshold: 2

  pa_enabled: true
  pa_seg_max_iterations: 100
  pa_seg_dist_threshold: 0.008
  pa_sac_plane_distance: 0.004
  pa_kdtree_radius: 0.016

  tr_search_radius: 0.01
  tr_mu: 20
  tr_nearest_neighbors: 400
  tr_max_surface_angle: 0.80
  tr_min_angle: 0.01
  tr_max_angle: 3.10
  tr_normal_consistency: true

  mls_upsampling_radius: 0.01
  mls_point_density: 100
  mls_search_radius: 0.04

  voxel_leaf: 0.004
  occupancy_threshold: 0.5
  use_tabletop_segmentation: false
  tabletop_seg_distance_thresh: 0.01
  ignore_largest_cluster: false
