int32 GENERATE_MOTION_PLAN=1
int32 GENERATE_MOTION_PLAN_AND_PREVIEW=2
int32 PREVIEW_TOOL_PATH=3
int32 PREVIEW_MOTION_PLAN=4
int32 EXECUTE_MOTION_PLAN=5

int32 action

bool use_default_parameters
godel_msgs/PathPlanningParameters params
godel_msgs/SurfaceBoundaries surface

---

bool succeeded

