<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	

	<xacro:include filename="$(find godel_robot_config)/urdf/asus_sensor_macro.xacro"/>
	<xacro:include filename="$(find keyence_ljv_description)/urdf/lj_v7080_macro.xacro"/>


	<!-- parameter list -->
	<xacro:property name="gripper_length" value="0.2"/>
	<xacro:property name="gripper_width" value="0.0"/>
	<xacro:property name="gripper_height" value="0.0"/>

	<xacro:macro name="blending_eff_definition" params="prefix eff_adjustment">

		<!-- link definition -->
			<link name="${prefix}eff_frame"/>

			<link name="${prefix}gripper_body">
				<visual>
					<geometry>
						<mesh filename="package://godel_robot_config/meshes/Deburring_eff.STL" />
					</geometry>
					<material name="silver">
						<color rgba="0.8 0.8 0.8 1"/>
					</material>
				</visual>
				<collision>
					<geometry>
						<mesh filename="package://godel_robot_config/meshes/Deburring_eff_Collision_Model.STL" />
					</geometry>
					<material name="another_blue2">
						<color rgba="0.38 0.54 0.83 1"/>
					</material>
				</collision>
			</link>

			<link name="${prefix}tcp_frame"/>
			<link name="${prefix}asus_mount"/>

			<link name="${prefix}keyence_mount"/>

		<xacro:asus_sensor_definitions prefix="${prefix}" parent_link="${prefix}asus_mount" 
				x_val="0.01479" y_val="0.006741" z_val="0.007162" roll="-3.123031" pitch="0.001618" yaw="0.02739"/>

		<!-- Keyence sensor -->
		<xacro:keyence_lj_v7080 prefix="${prefix}keyence_" />

		<link name="${prefix}keyence_tcp_frame" />
		<joint name="${prefix}keyence_to_keyence_tcp_frame" type="fixed">
			<parent link="${prefix}keyence_sensor_optical_frame"/>
			<child link="${prefix}keyence_tcp_frame"/>
			<origin rpy="0 3.14159 0"/>
		</joint>


		<!-- joint definitions -->
			<joint name="${prefix}gripper_to_palm" type="fixed">
				<parent link="${prefix}eff_frame"/>
				<child link="${prefix}gripper_body"/>
				<origin xyz="0 0 ${gripper_height * 0.5}" rpy="0 0 3.6651914"/>
			</joint>
		
			<joint name="${prefix}eff_frame_to_asus_mount" type="fixed">

				<parent link="${prefix}eff_frame"/>
				<child link="${prefix}asus_mount"/>
				<origin xyz="0 0 0.150" rpy="3.14 0 2.09"/>
			</joint>

			<joint name="${prefix}gripper_to_tcp" type="fixed">
				<parent link="${prefix}gripper_body"/>
				<child link="${prefix}tcp_frame"/>
				<origin xyz="${gripper_length} 0 ${eff_adjustment}" rpy="0 1.570796326 0"/>
			</joint>	

			<joint name="${prefix}gripper_to_keyence_mount" type="fixed">
				<parent link="${prefix}gripper_body" />
				<child link="${prefix}keyence_mount"/>
				<origin xyz="-0.16 0 0.08" rpy="0 1.570796326 0" />
			</joint>

			<joint name="${prefix}keyence_mount_to_keyence" type="fixed">
				<parent link="${prefix}keyence_mount"/>
				<child link="${prefix}keyence_base_link"/>
				<origin xyz="0 0 0" rpy="0 0 1.570796326"/>
			</joint>

	</xacro:macro>
</robot>
