<?xml version="1.0" ?>
<robot name="sia20d_workspace" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find motoman_sia20d_support)/urdf/sia20d_macro.xacro"/>
  <xacro:include filename="$(find godel_robot_config)/urdf/workspace_components_swri.xacro"/>
  <xacro:include filename="$(find godel_robot_config)/urdf/blending_eff_macro.xacro"/>
  
  <!-- property list -->
  <xacro:property name="workcell_height" value="1"/>
  <xacro:property name="coupler_height" value="0.0"/> <!--"0.087"-->
  <xacro:property name="arm_prefix" value=""/>
    
  <xacro:property name="no_go_height" value="0.1"/>

  <!-- instantiating workcell definitions -->
  <xacro:workcell_swri_zone1_components/>

  <!-- instantiating arm  --> 
  <xacro:motoman_sia20d prefix="${arm_prefix}"/>
  <!-- instantiating end effector -->
  <xacro:blending_eff_definition prefix="${arm_prefix}" eff_adjustment="0.0575"/>

  <!-- Connect tool0 to the end effector -->
  <joint name="link_t_to_eff" type="fixed">
    <parent link="tool0"/>
    <child link="eff_frame"/>
    <origin xyz="0 ${coupler_height} 0" rpy="0.0 0.0 3.1416"/>
  </joint>

  <!-- Connect the world_frame (defined in workcell components) and the robot -->
  <joint name="world_to_base" type="fixed">
    <parent link="world_frame"/>
    <child link="${arm_prefix}base_link"/>
    <origin xyz="0.241 0 0" rpy="0 0 0"/>
  </joint>

  <!-- As a work-around for the lack of collision detection with move-it joint
       moves with the work objects, we use a no-go-zone to prevent the robot
       from getting too close to the table. Descartes is still unawares, though -->
  <link name="no_go_zone">
    <collision>
      <geometry>
        <box size="0.8 2.220 ${no_go_height}"/>
      </geometry>
    </collision>  
  </link>

  <joint name="world_to_no_go" type="fixed">
    <parent link="world_frame" />
    <child link="no_go_zone" />
    <origin xyz="1.0 0 ${no_go_height/2.0} " />
  </joint>
   
</robot>
