<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	
	<xacro:include filename="$(find godel_calibration_config)/urdf/calib_kinect2_sensor_macro.xacro"/>

	<!-- parameter list -->
	<xacro:property name="gripper_length" value="0.2"/>
	<xacro:property name="gripper_width" value="0.0"/>
	<xacro:property name="gripper_height" value="0.0"/>

	<xacro:macro name="calib_blending_eff_definition" params="prefix eff_adjustment">

		<!-- link definition -->
			<link name="${prefix}eff_frame"/>

			<link name="${prefix}gripper_body">
				<visual>
					<geometry>
						<mesh filename="package://godel_robot_config/meshes/Deburring_eff.STL" />
					</geometry>
					<material name="silver">
						<color rgba="0.8 0.8 0.8 1"/>
					</material>
				</visual>
				<collision>
					<geometry>
						<mesh filename="package://godel_robot_config/meshes/Deburring_eff_Collision_Model.STL" />
					</geometry>
					<material name="another_blue2">
						<color rgba="0.38 0.54 0.83 1"/>
					</material>
				</collision>
			</link>

			<link name="${prefix}tcp_frame"/>
			<link name="${prefix}kinect2_mount"/>

		<xacro:calib_kinect2_sensor_definitions prefix="${prefix}" parent_link="${prefix}kinect2_mount" />

		<!-- joint definitions -->
			<joint name="${prefix}gripper_to_palm" type="fixed">
				<parent link="${prefix}eff_frame"/>
				<child link="${prefix}gripper_body"/>
				<origin xyz="0 0 ${gripper_height * 0.5}" rpy="0 0 3.6651914"/>
			</joint>
		

			<joint name="${prefix}eff_frame_to_kinect2_mount" type="fixed">
				<parent link="${prefix}eff_frame"/>
				<child link="${prefix}kinect2_mount"/>
				<origin xyz="0 0 0.150" rpy="3.14 0 ${2.09+3.141592653589793}"/>
			</joint>

			<joint name="${prefix}gripper_to_tcp" type="fixed">
				<parent link="${prefix}gripper_body"/>
				<child link="${prefix}tcp_frame"/>
				<origin xyz="${gripper_length} 0 ${eff_adjustment}" rpy="0 1.570796326 0"/>
			</joint>

	</xacro:macro>
</robot>
