sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    # TODO: use appropriate cloud input topic
    point_cloud_topic: godel_octomap_input
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.05
    padding_scale: 1
    filtered_cloud_topic: godel_octomap_filtered_cloud
    # TODO: determine if self masking is necessary
    self_mask:
        min_sensor_dist: 0.8
        self_see_default_padding: .04
        self_see_default_scale: 1.0
        self_see_links:
            - name: base_link
              # padding: 0.2
            - name: link_1
              # padding: 0.2 
            - name: link_2
              # padding: 0.06
            - name: link_3
              # padding: 0.06 
            - name: link_4
              # padding: 0.06 
            - name: link_5
              # padding: 0.06 
            - name: link_6
              # padding: 0.06 

            # TODO: add additional links (eef)
