# Plan Parameters
float64 discretization  # (m) How densely to space adjacent Cartesian points
float64 margin          # (m) additional distance to leave near surface boundaries
float64 overlap         # (m) overlap distance between adjacent paths
float64 scan_width      # (m) width of scanner's beam
float64 tool_radius     # (m) radius of effector tool (e.g. blending pad)
float64 traverse_height # (m) The minimum distance (z-axis) required to safely traverse
